[workspace]
members = [
    "cargo-dist",
    "cargo-dist-schema",
]

[workspace.metadata.release]
shared-version = true
tag-name = "v{{version}}"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
