name: Installers

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "11 7 * * 1,4"

jobs:
  shell-installer-on-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust
        run: rustup update 1.67.1 --no-self-update && rustup default 1.67.1
      - name: Run cargo-dist on cargo-dist
        run: cd cargo-dist && cargo run -- dist
      - name: Run file on generated installer
        run: file target/distrib/cargo-dist-v0.0.4-installer.sh
      - name: Run the installer 
        run: chmod +x target/distrib/cargo-dist-v0.0.4-installer.sh && target/distrib/cargo-dist-v0.0.4-installer.sh

  shell-installer-on-mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust
        run: rustup update 1.67.1 --no-self-update && rustup default 1.67.1
      - name: Run cargo-dist on cargo-dist
        run: cd cargo-dist && cargo run -- dist
      - name: Run file on generated installer
        run: file target/distrib/cargo-dist-v0.0.4-installer.sh
      - name: Run the installer 
        run: chmod +x target/distrib/cargo-dist-v0.0.4-installer.sh && target/distrib/cargo-dist-v0.0.4-installer.sh

  power-shell-installer:
    runs-on: windows-latest
    steps:
      - name: Install Rust
        run: rustup update 1.67.1 --no-self-update && rustup default 1.67.1
      - name: Run cargo-dist installer
        run: irm https://github.com/axodotdev/cargo-dist/releases/download/v0.0.4/cargo-dist-v0.0.4-installer.ps1 | iex
      - name: Run cargo-dist
        run: cargo dist --help
